---
title: "p8105_hw3_ar4173"
author: "Anand Rajan"
date: "10/17/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1

```{r}
library(p8105.datasets)
data("instacart")

instacart
```

```{r eval=FALSE, warning=FALSE}
From opening the dataset, we see there are 1,384,617 observations and 15 variables. 
```



```{r}
instacart_df =
  instacart %>% 
  group_by(aisle) %>% 
  summarize(n_obs =n()) %>% 
  arrange(desc(n_obs)) %>% 
  mutate(
    product_rank=order(n_obs,decreasing=TRUE)
  )

instacart_df



instacart %>% 
  group_by(department) %>% 
  summarize(n_obs=n())

instacart %>% 
  group_by(order_id, user_id) %>% 
  summarize(
    mean_days_prior=mean(days_since_prior_order)
  )



```


```{r}
instacart_plot = 
  instacart_df %>% 
  filter(n_obs > 10000)

ggplot(instacart_plot, aes(x= product_rank , y=n_obs)) + geom_point(aes(color=aisle))
```




```{r}
popular_items =
  instacart %>%
  filter(
    aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")
  ) %>% 
  group_by(aisle) %>% 
  count(product_name, name="order_count") %>% 
  mutate(
    product_rank = min_rank(desc(order_count))
  ) %>% 
  filter(product_rank <= 3) %>% 
  select(-product_rank) 


  knitr::kable(popular_items, format="markdown")

```


```{r}

order_hour =
  instacart %>% 
  mutate(
    order_dow = recode(order_dow, 
                       "0"="Sunday", 
                       "1"="Monday", 
                       "2"="Tuesday", 
                       "3"="Wednesday", 
                       "4"="Thursday", 
                       "5"="Friday", 
                       "6"="Saturday")
  ) %>% 
  group_by(product_name, order_dow) %>%
  filter(
    product_name %in% c("Pink Lady Apples","Coffee Ice Cream")) %>% 
  summarize(mean_hour=(mean(order_hour_of_day))) %>% 
  mutate(
    day_of_the_week=ordered(order_dow,c("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"))
  ) %>% 
  arrange(day_of_the_week) %>% 
  select(-order_dow) %>% 
  pivot_wider(
    names_from="day_of_the_week",
    values_from="mean_hour"
  )


knitr::kable(order_hour,format="markdown")
```

## problem 2

```{r}
data("brfss_smart2010")

health_brfss=
force(brfss_smart2010) %>% 
  janitor::clean_names() %>% 
  filter(topic=="Overall Health" ) %>% 
  filter(response %in% c("Poor","Fair","Good","Very Good","Excellent")) %>% 
  arrange(desc(response))
  

```

```{r}
health_brfss %>%
  filter(year==2002) %>%
  group_by(locationabbr) %>% 
  summarize(n_obs = n()) %>% 
  filter(n_obs>=7)

health_brfss %>%
  filter(year==2010) %>%
  group_by(locationabbr) %>% 
  summarize(n_obs = n()) %>% 
  filter(n_obs>=7)
```


```{r}
mean_data = 
health_brfss %>%
  filter(response=="Excellent") %>% 
  drop_na(data_value) %>% 
  group_by(locationabbr,year) %>% 
  mutate(
    mean_data_value=mean(data_value)
  ) %>% 
  select(year,locationabbr,mean_data_value) %>% 
  distinct()

ggplot(mean_data, aes(x=year, y=mean_data_value, color=locationabbr)) +geom_line(se=FALSE)



```



```{r}

health_brfss %>% 
  filter(year== "2006" | year=="2010" , locationabbr=="NY") %>%
  ggplot(aes(x=locationdesc, y= data_value)) + geom_point()

facet_grid(.~year)
  
  




```

